hallu_detect:
  data:
    # 数据根目录（相对于项目根目录）
    data_root: "../data"
    # 结果输出根目录（相对于项目根目录），每个数据集结果保存在各自子目录下
    output_root: "../data"
    # 自定义输出的 parquet 文件名
    output_filename: "qwen3.5_2b_tk.parquet"
    # 需要处理的数据集列表（与 data/ 下子目录名一致）
    datasets:
      - AggreFact-CNN
      - AggreFact-XSum
      - COVID-Fact
      - ExpertQA
      # - Reveal
      - SCIFACT
      - minicheck
      - pubhealth
      - summeval

  model:
    max_new_tokens: 10240
    temperature: 0.6
    top_p: 0.95
    top_k: 20
    repetition_penalty: 1.3
    enable_thinking: true

  inference:
    engine_type: "vllm" # "vllm" | "api" | "nli"

    # vLLM 参数（engine_type="vllm" 时生效）
    vllm_model_path: "../models/llms/Qwen3.5-2B"
    vllm_gpu_memory_utilization: 0.92
    vllm_tensor_parallel_size: 1
    vllm_max_model_len: 40960
    vllm_max_num_seqs: 96            # vLLM 允许的最大并发数（控制每批次处理的最大序列数）
    vllm_enable_chunked_prefill: true

    # API 参数（engine_type="api" 时生效）
    api_base_url: "https://gpt-agent.cc/v1"
    api_key: "sk-DPqQvcmYAoCbjspIHCWR0MeSHnWuK3QhxHmom1FjycQqfnS1"
    api_model_name: "gpt-5.4"
    api_max_workers: 10
    save_every_n_items: 100

    # NLI 参数（engine_type="nli" 时生效）
    nli_model_path: "../models/nlis/DeBERTa-v3-base"
    nli_max_length: 512
    # nli_entailment_id: 1    # 3-class: entailment=2; 2-class: entailment=1

    test_limit: 0
